### PR TITLE
Fix #7 Invalid SPDX generated when config file is not found

### LINKED ISSUE #7: Invalid SPDX generated when config file is not found
When config file is not found, the program should stop with an error message and not create an invalid SPDX file.

```
compose -d NSP-22-9-test1 -s NSP-22-9-test1.spdx

...generating composed SPDX document from directory: NSP-22-9-test1
...using config: config.yaml
failed reading yaml file
 open config.yaml: no such file or directory
...document saved to NSP-22-9-test1.spdx in "tv" format
```

Examples of invalid SPDX generated as it has no value for "packageName":
```
##### Package:
SPDXID: SPDXRef-Package-
```

```
##### Relationships
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-
Relationship: SPDXRef-- DESCRIBES SPDXRef-NSP-22-9-test1-
Relationship: SPDXRef-- DESCRIBES SPDXRef-analytics-action-processor-app-22-9-0-rel-image-
```

### PR DESCRIPTION
**Pull request by vargenau**
Fix #7 Invalid SPDX generated when config file is not found

Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

### CODE REVIEW

File: parser/config.go [hunk 1]
```diff
@@ -103,7 +104,8 @@ func readConfFile(file string) []byte {
 	conf, err := ioutil.ReadFile(file)
 
 	if err != nil {
-		fmt.Println("failed reading yaml file\n", err)
+		fmt.Println("Error: failed reading yaml file. SPDX document not generated.\n")
```
Comment (ivanayov) [inline parser/config.go:107]: The convention in go it to stick to lower case, i.e. "error:...", not a big deal for that though.
I think we should not omit the error, as those are not always so intuitive and in some use-cases might be really hard for the user to resolve it without any detail.

**Review by ivanayov — COMMENTED** [review]
Thank you for addressing this, @vargenau! Fully agree with your proposal.

I left a minor comment..

File: parser/config.go (hunk 1 above)
Comment (vargenau) [reply parser/config.go:107]: No issue with lower case if it is your convention.

I removed the "err" on purpose as it is redundant with the error message and adds no new information. Add it again if you prefer. What should stay is "SPDX document not generated".
